/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alternativetags.c"
#include "bar_ewmhtags.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_taglabels.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "aspectresize.c"
#include "attachx.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "fakefullscreenclient.c"
#include "floatpos.c"
#include "keymodes.c"
#include "maximize.c"
#include "moveplace.c"
#include "moveresize.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "reorganizetags.c"
#include "restartsig.c"
#include "renamed_scratchpads.c"
#include "shift.c"
#include "shiftboth.c"
#include "shifttag.c"
#include "shifttagclients.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swallow.c"
#include "tagall.c"
#include "tagallmon.c"
#include "tapresize.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "warp.c"
#include "zoomswap.c"
#include "xrdb.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_monocle.c"
#include "layout_tile.c"

