/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "fakefullscreenclient.h"
#include "floatpos.h"
#include "focusdir.h"
#include "keymodes.h"
#include "moveplace.h"
#include "moveresize.h"
#include "movestack.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "shift.h"
#include "shiftviewclients.h"
#include "sticky.h"
#include "swallow.h"
#include "tagall.h"
#include "tagallmon.h"
#include "tapresize.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "warp.h"
#include "zoomswap.h"
/* Layouts */
#include "layout_monocle.h"
#include "layout_tile.h"

